spring.data.rest.base-path=/api
spring.jpa.show-sql=true

#LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/project_manager
spring.datasource.username=postgres
spring.datasource.password=admin

#JPA/hibernate ei tee muutoksia ulkoiseen kantaan
spring.jpa.hibernate.ddl-auto=none